/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StartHereRouteImport } from './routes/start-here'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as DesignHistoryRouteImport } from './routes/design.history'
import { Route as KitKitIdRouteImport } from './routes/kit.$kitId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'
import { Route as DesignHistoryDiffRouteImport } from './routes/design.history.diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StartHereRoute = StartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignHistoryRoute = DesignHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DesignRoute,
} as any)
const KitKitIdRoute = KitKitIdRouteImport.update({
  id: '/kit/$kitId',
  path: '/kit/$kitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignHistoryDiffRoute = DesignHistoryDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => DesignHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/compare': typeof CompareRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/start-here': typeof StartHereRoute
  '/studio': typeof StudioRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/compare': typeof CompareRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/start-here': typeof StartHereRoute
  '/studio': typeof StudioRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/compare': typeof CompareRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/start-here': typeof StartHereRoute
  '/studio': typeof StudioRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/p/$slug': typeof PSlugRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/compare'
    | '/design'
    | '/library'
    | '/settings'
    | '/start-here'
    | '/studio'
    | '/design/history'
    | '/kit/$kitId'
    | '/p/$slug'
    | '/share/$shareToken'
    | '/design/history/diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/compare'
    | '/design'
    | '/library'
    | '/settings'
    | '/start-here'
    | '/studio'
    | '/design/history'
    | '/kit/$kitId'
    | '/p/$slug'
    | '/share/$shareToken'
    | '/design/history/diff'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/compare'
    | '/design'
    | '/library'
    | '/settings'
    | '/start-here'
    | '/studio'
    | '/design/history'
    | '/kit/$kitId'
    | '/p/$slug'
    | '/share/$shareToken'
    | '/design/history/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  CompareRoute: typeof CompareRoute
  DesignRoute: typeof DesignRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  StartHereRoute: typeof StartHereRoute
  StudioRoute: typeof StudioRoute
  KitKitIdRoute: typeof KitKitIdRoute
  PSlugRoute: typeof PSlugRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-here': {
      id: '/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof StartHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/history': {
      id: '/design/history'
      path: '/history'
      fullPath: '/design/history'
      preLoaderRoute: typeof DesignHistoryRouteImport
      parentRoute: typeof DesignRoute
    }
    '/kit/$kitId': {
      id: '/kit/$kitId'
      path: '/kit/$kitId'
      fullPath: '/kit/$kitId'
      preLoaderRoute: typeof KitKitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/history/diff': {
      id: '/design/history/diff'
      path: '/diff'
      fullPath: '/design/history/diff'
      preLoaderRoute: typeof DesignHistoryDiffRouteImport
      parentRoute: typeof DesignHistoryRoute
    }
  }
}

interface DesignHistoryRouteChildren {
  DesignHistoryDiffRoute: typeof DesignHistoryDiffRoute
}

const DesignHistoryRouteChildren: DesignHistoryRouteChildren = {
  DesignHistoryDiffRoute: DesignHistoryDiffRoute,
}

const DesignHistoryRouteWithChildren = DesignHistoryRoute._addFileChildren(
  DesignHistoryRouteChildren,
)

interface DesignRouteChildren {
  DesignHistoryRoute: typeof DesignHistoryRouteWithChildren
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignHistoryRoute: DesignHistoryRouteWithChildren,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  CompareRoute: CompareRoute,
  DesignRoute: DesignRouteWithChildren,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  StartHereRoute: StartHereRoute,
  StudioRoute: StudioRoute,
  KitKitIdRoute: KitKitIdRoute,
  PSlugRoute: PSlugRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
